### ISSUE TITLE
FR: Automatically create tags

### ISSUE THREAD

**Issue by silvio** [roman-r-m/joplin-inline-tags-plugin#1]
If a tag is used in the body text, which does not exist yet, it would be good if this tag is created. 

It is sufficient to create the tag only when the document is saved or the return key is pressed or synchronization is started.

**Comment by roman-r-m** [comment]
It's already implemented. Which version you're using?

**Comment by silvio** [comment]
Oh. I installed the plugin normally in the desktop app via "`tools` -> `options` -> `plugins`".
I can't tell you which version is behind it.

**Comment by roman-r-m** [comment]
If you type `#` then some text, e.g. `newtag` don't you get an option `Create new tag: newtag`

**Comment by silvio** [comment]
Ah - okay, I had an outdated Joplin version installed. Now I see version number (0.0.4) as well as "Create new Tag" entry. Thanks for that!

I find it a bit inconvenient to select this "Create new Tag" though, it disrupts the writing flow a bit. Is it possible to have the tags created automatically without asking? And if the tags are already assigned then just ignore them.

@roman-r-m Thanks for this plugin! :-)

**Comment by roman-r-m** [comment]
> Is it possible to have the tags created automatically without asking?

I am not sure if it's a good idea, what it you made a typo?

**Comment by silvio** [comment]
As in other systems, don't care about the user's mistakes. The user can correct and will certainly do so.

**Comment by roman-r-m** [comment]
I suggest you raise it on the forum. I do not have a strong opinion on this as I almost never use tags.
