### ISSUE TITLE
Does not work on desktop Mac

### ISSUE THREAD

**Issue by ismoli** [roman-r-m/joplin-inline-tags-plugin#2]
Joplin Version 1.6.8.
Plugin installed through preferences.

Completely not working. No popups after typing "#"

**Comment by roman-r-m** [comment]
It needs Joplin 1.7+ which is only available as pre-release at this point.

**Comment by roman-r-m** [comment]
The manifest had min version 1.6 by mistake.

**Comment by ismoli** [comment]
Thanks, works in 1.7.
Is it possible to make it work in rich mode editor?

**Comment by roman-r-m** [comment]
>  Is it possible to make it work in rich mode editor?

No. That editor is completely different so the plugin has to be implemented from scratch. Plus Joplin plugin API has no support for plugins for that editor. In fact, I am not sure the editor itself supports plugins.
