### ISSUE TITLE
Feature: Change text when a tag label has been changed

### ISSUE THREAD

**Issue by Galliver7** [roman-r-m/joplin-inline-tags-plugin#3]
I've tagged some tag like "#foo" and changed it later on ( like "bar" ) then it is keeping the original text ( which is "#foo").
It will be cool feature when the text had been changed, then the text in a note too.

Hope this idea make this great stuff better : )

**Comment by roman-r-m** [comment]
The current API does not have a way for a plugin to know when a tag is renamed so this isn't possible at the moment.
