### ISSUE TITLE
delete joplin tag too, when tag in text is deleted

### ISSUE THREAD

**Issue by itge13** [roman-r-m/joplin-inline-tags-plugin#4]
when i delete the text "#tag" the joplin tag still stays and I have to remove it manually. is it possible to delete it altogether, when the tag in text is deleted?

**Comment by roman-r-m** [comment]
Hi itge13.

It seems this feature is pretty complicated to implement properly as there are lots of edge cases e.g. what if you delete just one symbol from tag, should it be renamed, etc. And the benefits aren't very clear to me.

For this reason I am not going to implement this, at least not anytime soon, sorry.

**Comment by itge13** [comment]
couldnt find it but thanks for considering it.
